import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <ClerkProvider appearance={
        {baseTheme: dark}
      }>
        <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* header */}
            <Header/>
            <main className="min-h-screen">
              {children}
            </main>
            <Toaster richColors/>
            {/* footer */}
            <footer
            className="bg-muted/50 py-12"
            >
              <div className="container mx-auto px-4 text-center text-gray-200">
              Made with ❤️ by Sejal Godbole
            </div>
            </footer>
          </ThemeProvider>      
      </body>
        </ClerkProvider>
    </html>
  );
}
