"use client";

import { useState, useEffect } from "react";
import { Loader2, Flame, Github } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { roastGithubProfile, getLastRoast } from "@/actions/roastGithub";
import { toast } from "sonner";
import ReactMarkdown from "react-markdown"; // <--- IMPORT THIS

export default function GithubRoastPage() {
  const [username, setUsername] = useState("");
  const [roast, setRoast] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetchLastRoast = async () => {
      const lastRoast = await getLastRoast();
      if (lastRoast) {
        setRoast(lastRoast.content);
        setUsername(lastRoast.username);
      }
    };
    fetchLastRoast();
  }, []);

  const handleRoast = async (e) => {
    e.preventDefault();
    if (!username.trim()) return;

    setLoading(true);
    setRoast(""); 

    try {
      const response = await roastGithubProfile(username);
      
      if (response.error) {
        toast.error(response.error);
      } else {
        setRoast(response.content);
        toast.success("Roast generated & saved!");
      }
    } catch (error) {
      toast.error("Something went wrong.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container mx-auto p-6 space-y-8 max-w-3xl">
      <div className="text-center space-y-2">
        <p className="text-muted-foreground">
          Enter a GitHub username and let AI destroy your coding ego.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Who are we roasting today?</CardTitle>
          <CardDescription>Enter the GitHub username below.</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleRoast} className="flex gap-4">
            <Input
              placeholder="e.g. sejal-godbole"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              disabled={loading}
              className="flex-1"
            />
            <Button type="submit" disabled={loading} variant="destructive">
              {loading ? <Loader2 className="animate-spin mr-2" /> : <Github className="mr-2 h-4 w-4" />}
              Roast Me
            </Button>
          </form>
        </CardContent>
      </Card>

      {roast && (
        <Card className="border-blue-500/50 bg-blue-500/5 animate-in fade-in slide-in-from-bottom-4">
          <CardHeader>
            <CardTitle className="text-blue-700 dark:text-blue-400 flex items-center gap-2">
              <Flame className="h-5 w-5" />
              The Verdict for {username}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {/* UPDATED MARKDOWN SECTION */}
            <div className="text-lg leading-relaxed mb-6">
              <ReactMarkdown
                components={{
                  // Customizing how markdown elements look in Tailwind
                  strong: ({node, ...props}) => <span className="font-bold text-foreground" {...props} />,
                  em: ({node, ...props}) => <span className="italic text-foreground/80" {...props} />,
                  code: ({node, ...props}) => <span className="bg-muted px-1.5 py-0.5 rounded font-mono text-sm font-semibold" {...props} />,
                  p: ({node, ...props}) => <p className="mb-4 last:mb-0" {...props} />,
                }}
              >
                {roast}
              </ReactMarkdown>
            </div>
          </CardContent>
          <CardFooter className="flex flex-col items-center justify-center border-t border-blue-500/20 pt-4 pb-6">
             <div className="text-4xl mb-3 animate-bounce">
                😂😂💀
             </div>
             <p className="text-sm text-muted-foreground italic text-center">
                (Disclaimer: This roast is generated by AI purely for entertainment purposes. <br/> Please don&apos;t take it personally! 😉)
             </p>
          </CardFooter>
        </Card>
      )}
    </div>
  );
}